name: Dependency Review

on: pull_request

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Dependency Review
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
