name: Builds, tests & co

on:
  - push
  - pull_request

jobs:
  hygiene:
    name: Hygiene

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        run: yarn install --immutable

      - name: Check formatting
        run: yarn fmt:check

      - name: Check lint
        run: yarn lint

      - name: Check type
        run: yarn typecheck

  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Use latest Packer
        uses: ./
